### ISSUE TITLE
Logins are insecure

### ISSUE THREAD

**Issue by lwob** [foleyfactor/Intercode#1]
There's no SSL certificate on the login page

![image](https://user-images.githubusercontent.com/6954807/29278275-42967a4c-80e2-11e7-8d3f-a7eb528ed984.png)

You're welcome

**Comment by lwob** [comment]
# **This may be helpful**
![image](https://user-images.githubusercontent.com/6954807/29278786-c3378be0-80e3-11e7-98b7-eff2fa37160e.png)

**Comment by foleyfactor** [comment]
Thanks for the issue, @lwob. I've updated the page to load over https.
